### ISSUE TITLE
[PaLM API - Chatbot Ext.] Context Field not working 

### ISSUE THREAD

**Issue by Ace-uff-Spades** [GoogleCloudPlatform/firebase-extensions#207]
- Extension name: Chatbot with PaLM API
- Extension version: 0.1.7
- Configuration values: Palm API Provider: vertex
API Key (Generative Language AI for Developers Provider ONLY) (Optional): Parameter not set
Collection Path: discussions
Prompt Field: prompt
Response Field: response
Order Field (Optional): Parameter not set
Cloud Functions location: us-east1
Language model: chat-bison
**Context (Optional): Speak like Shakespeare.**
Temperature (Optional): 0.8
Nucleus sampling probability (Optional): Parameter not set
Sampling strategy parameter (Optional): Parameter not set
Candidate count (Optional): 1
Candidates field (Optional): candidates
Enable per document overrides: no

### Describe the problem
I'm using the chatbot api in an app and it works as expected. However, when I set the context field for the chatbot to act a certain way, it doesn't follow it. I tried with multiple context prompts and none of them work because I get the same response before and after setting the context field.

#### Steps to reproduce:

What happened? How can we make the problem occur?
1. Download and set the parameters of the extension as stated above but keep the context field and the temperature blank.
2. Create a collection in Firestore called "discussions" 
3. Input in a prompt field with a question. 
4. Wait for the extension to post a response. 
5. Go back to the extension's configuration page and add "Speak like Shakespeare", in the context field. Keep the temperature field blank.
6. Retry the same prompt as above and compare the two results. 

##### Expected result
The two responses are different and the answer is stated in the voice of Shakespeare. 

##### Actual result
The two responses are identical and the answer with previous context doesn't apply to the response from the Chatbot.

**Comment by jhuleatt** [comment]
It looks like this happens because the overrides logic for the extension is missing the truthy check that other overrides have, so `context` is always set to `undefined` if it isn't included in each document in the chat:

https://github.com/GoogleCloudPlatform/firebase-extensions/blob/264198e27ad841f421598fc8b1eb005edce825e7/firestore-palm-chatbot/functions/src/index.ts#L175-L177

Compare this to the other overrides which have the `if(<overridename>)` check: 

https://github.com/GoogleCloudPlatform/firebase-extensions/blob/264198e27ad841f421598fc8b1eb005edce825e7/firestore-palm-chatbot/functions/src/index.ts#L181-L183

**Comment by cabljac** [comment]
Thanks for raising this! Will look into this ASAP

**Comment by cabljac** [comment]
I'll aim to get a fix merged in and released tomorrow morning :)

**Comment by cabljac** [comment]
I have a PR in to fix this, just waiting on review and then I will cut a release
