### ISSUE TITLE
Chatbot with PaLM API - Add ability to configure safety settings

### ISSUE THREAD

**Issue by Theunodb** [GoogleCloudPlatform/firebase-extensions#213]
Extension name
This feature request is for extension: firestore-palm-chatbot

### What feature would you like to see?
It would be nice to be able to configure the [safety settings](https://developers.generativeai.google/guide/safety_setting) for the Language Tasks with PaLM API extension. We can configure these settings in the API directly and in MakerSuite but not in Firebase.

Similar to this request:
https://github.com/GoogleCloudPlatform/firebase-extensions/issues/176

### How would you use it?
We are currently making use of a chatbot where you chat with your own medical results. Our need is to only chat to the provided results, without any medical restrictions

**Comment by cabljac** [comment]
Hey there, this is a limitation of the PaLM API rather than a limitation of the extension I think.

<img width="929" alt="Screenshot 2023-10-18 at 09 47 11" src="https://github.com/GoogleCloudPlatform/firebase-extensions/assets/32874567/3e2bbce0-e417-4983-bea6-9210bd506120">

https://developers.generativeai.google/models/language

As an alternative, the text-bison model has configurable safety settings. As far as I understand, it is fine-tuned to handle "language tasks". With some clever prompting perhaps it will perform well as a chatbot. The disadvantage here is that the language tasks extension isn't set up to work like a chatbot.

**Comment by cabljac** [comment]
I have been thinking of extracting out the "chatbot" logic into either a package or its own more generic extension at some point, which would be good for your use-case
